package dk.northtech.dassco_specify_adapter.domain.specify;

import java.util.List;

public class Agent {
    public Integer id;
    public String abbreviation;
    public Integer agenttype;
    public String date1;
    public Integer date1precision;
    public String date2;
    public Integer date2precision;
    public String dateofbirth;
    public Integer dateofbirthprecision;
    public String dateofdeath;
    public Integer dateofdeathprecision;
    public Integer datetype;
    public String email;
    public String firstname;
    public String guid;
    public String initials;
    public Integer integer1;
    public Integer integer2;
    public String interests;
    public String jobtitle;
    public String lastname;
    public String middleinitial;
    public String remarks;
    public String suffix;
    public String text1;
    public String text2;
    public String text3;
    public String text4;
    public String text5;
    public String timestampcreated;
    public String timestampmodified;
    public String title;
    public String url;
    public String verbatimdate1;
    public String verbatimdate2;
    public Integer version;
    public String collcontentcontact;
    public String colltechcontact;
    public String createdbyagent;
    public String division;
    public String instcontentcontact;
    public String insttechcontact;
    public String modifiedbyagent;
    public String organization;
    public String specifyuser;
    public List<Object> addresses;
    public String orgmembers;
    public List<Object> agentattachments;
    public List<Object> agentgeographies;
    public List<Object> identifiers;
    public List<Object> agentspecialties;
    public List<Object> variants;
    public String collectors;
    public List<Object> groups;
    public String members;
    public String resource_uri;
}
