spring.application.name=dassco-specify-adapter
spring.servlet.multipart.enabled=true

server.port=8081

auth.keycloak.realm=${KEYCLOAK_REALM:dassco}
auth.serverRootUrl=${KEYCLOAK_AUTH_SERVER_URL:http://localhost:8083/keycloak/}
auth.clientName=${KEYCLOAK_RESOURCE:dassco-asset-service}
auth.serverUrl=${auth.serverRootUrl}realms/${auth.keycloak.realm}

spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${auth.serverUrl}/protocol/openid-connect/certs

file-proxy.rootUrl=${FILE_PROXY_ROOT_URL:http://localhost:8080}


amqp-config.acknowledgeQueueName=${ACKNOWLEDGE_QUEUE:acknowledge-queue}
amqp-config.assetQueueName=${ASSET_QUEUE:asset-queue}

amqp-config.host=${AMQP_HOST_NAME:localhost}
amqp-config.secure=${AMQP_SECURE:false}

# This is required for use with the Web Portal.
# Enables the 'getfileref' and '/static/...' URLs.
# web asset service settings.py -> ALLOW_STATIC_FILE_ACCESS = True
asset-service.allowStaticFileAccess=${ALLOW_STATIC_FILE_ACCESS:true}
asset-service.rootUrl=${ASSET_SERVICE_ROOT_URL:http://localhost:8084/ars}
asset-service.fileFriendlyPostfix=${FILE_FRIENDLY_POSTFIX:specify-001}
asset-service.tokenKey=${TOKEN_KEY:test_attachment_key}
asset-service.tokenTimeToleranceSeconds=${TOKEN_TIME_TOLERANCE_SECONDS:150}
asset-service.tokenRequiredForGet=${TOKEN_REQUIRED_FOR_GET:false}
asset-service.institution=${INSTITUTION:NHMD}

specify.rootUrl=${SPECIFY_URL:https://specify-test3.science.ku.dk}
specify.assetServer=${SPECIFY_ASSET_SERVER:https://testify-media.science.ku.dk}
specify-mappings.location=${SPECIFY_MAPPINGS_LOCATION:C:/Users/Thomas/Documents/specify-adapter/mappings/}
specify.username = ${SPECIFY_USERNAME}
specify.password = ${SPECIFY_PASSWORD}

keycloak.service-user.keycloakUrl=${auth.serverRootUrl}
keycloak.service-user.realm=${auth.keycloak.realm}
keycloak.service-user.clientId=${KEYCLOAK_SERVICE_USER_CLIENT_ID:rabbitmq-service-user}
keycloak.service-user.clientSecret=${KEYCLOAK_SERVICE_USER_CLIENT_SECRET:kbOFBXI9tANgKUq8vXHLhT6YhbivgXxn}





# Need to have an application-local.properties file with specify.username and specify.password!
spring.config.import=optional:file:./application-local.properties
