package dk.northtech.dassco_specify_adapter.domain;

public enum AcknowledgeStatus {
    SUCCESS,
    FILE_UPLOAD_ERROR,
    FILE_DOWNLOAD_ERROR,
    SPECIMEN_NOT_FOUND_ERROR,
    METADATA_UPLOAD_ERROR,
    UNKNOWN_ERROR,
    MAPPING_ERROR,
    PARKED_FILE_UPLOAD_ERROR,
    PARKED_FILE_DOWNLOAD_ERROR,
    PARKED_FILE_PATH_ERROR
}
