#Always take the first entry in file_formats
origfilename=${asset_guid}.${file_format}
attachmentlocation=${asset_pid}
copyrightdate=${date_asset_deleted}
filecreateddate=${date_asset_taken}
#Firste entry in file_formats, lowercase
mimetype=${file_format}
copyrightholder=${legality.copyright}
credit=${legality.credit}
license=${legality.license}
ispublic=${make_public}
remarks=${specify_attachment_remarks}
title=${specify_attachment_title}